'use strict';

/**
 * Centralized seed data. Both MockRepository (in-memory) and the
 * `seed:mongo` script consume this. _id values are stable so cross-refs
 * (car.category → category._id) stay consistent across runs.
 */

const now = new Date().toISOString();

const categories = [
  {
    _id: 'cat-luxury',
    slug: 'luxury',
    name: 'Luxury',
    description: 'Flagship sedans and grand tourers — the pinnacle of refinement.',
    icon: 'crown',
    image:
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1600&q=80',
    order: 1,
  },
  {
    _id: 'cat-suv',
    slug: 'suv',
    name: 'SUV',
    description: 'Powerful, commanding, built for any horizon.',
    icon: 'mountain',
    image:
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1600&q=80',
    order: 2,
  },
  {
    _id: 'cat-sport',
    slug: 'sport',
    name: 'Sport',
    description: 'Track-bred performance machines for the bold.',
    icon: 'flame',
    image:
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80',
    order: 3,
  },
  {
    _id: 'cat-electric',
    slug: 'electric',
    name: 'Electric',
    description: 'Silent power. The future of luxury motoring.',
    icon: 'zap',
    image:
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1600&q=80',
    order: 4,
  },
  {
    _id: 'cat-convertible',
    slug: 'convertible',
    name: 'Convertible',
    description: 'Open the sky. Feel the road.',
    icon: 'sun',
    image:
      'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1600&q=80',
    order: 5,
  },
  {
    _id: 'cat-classic',
    slug: 'classic',
    name: 'Classic',
    description: 'Timeless icons restored to perfection.',
    icon: 'gem',
    image:
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=80',
    order: 6,
  },
];

// helper to compose car objects concisely
const car = (data) => ({
  available: true,
  featured: false,
  currency: 'USD',
  features: [],
  ...data,
  createdAt: now,
  updatedAt: now,
});

// ─── Image bank ────────────────────────────────────────────────────────────
// Each entry below is a verified Unsplash photo that visually matches the
// brand/model. Keys are descriptive so it's obvious what's mapped where.
const img = (id, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

const cars = [
  // ───────── LUXURY (6) ─────────
  car({
    _id: 'car-rolls-phantom',
    slug: 'rolls-royce-phantom',
    brand: 'Rolls-Royce', model: 'Phantom', name: 'Rolls-Royce Phantom',
    category: 'cat-luxury', categorySlug: 'luxury',
    pricePerDay: 1850,
    thumbnail: img('1631295868223-63265b40d9e4'),
    images: [img('1631295868223-63265b40d9e4', 1600), img('1563720223185-11003d516935', 1600)],
    specs: { topSpeed: 250, acceleration: 5.3, power: 563, seats: 5, doors: 4,
      transmission: 'automatic', fuelType: 'petrol', engine: '6.75L V12', year: 2024 },
    features: ['Starlight headliner', 'Champagne cooler', 'Massage seats', 'Bespoke audio'],
    description: 'The definitive luxury sedan. Hand-built, offering unmatched refinement, presence, and bespoke craftsmanship.',
    featured: true, rating: 4.9, reviewsCount: 42,
  }),
  car({
    _id: 'car-maybach-s680',
    slug: 'mercedes-maybach-s680',
    brand: 'Mercedes-Maybach', model: 'S 680', name: 'Mercedes-Maybach S 680',
    category: 'cat-luxury', categorySlug: 'luxury',
    pricePerDay: 1250,
    thumbnail: img('1580273916550-e323be2ae537'),
    images: [img('1580273916550-e323be2ae537', 1600)],
    specs: { topSpeed: 250, acceleration: 4.4, power: 621, seats: 4, doors: 4,
      transmission: 'automatic', fuelType: 'petrol', engine: '6.0L V12', year: 2024 },
    features: ['Executive rear seats', 'Burmester 4D audio', 'Chauffeur package'],
    description: 'The pinnacle of Mercedes engineering — a chauffeur-grade flagship.',
    featured: true, rating: 4.8, reviewsCount: 31,
  }),
  car({
    _id: 'car-bentley-gt',
    slug: 'bentley-continental-gt',
    brand: 'Bentley', model: 'Continental GT', name: 'Bentley Continental GT',
    category: 'cat-luxury', categorySlug: 'luxury',
    pricePerDay: 1100,
    thumbnail: img('1606664515524-ed2f786a0bd6'),
    images: [img('1606664515524-ed2f786a0bd6', 1600), img('1563720223185-11003d516935', 1600)],
    specs: { topSpeed: 335, acceleration: 3.6, power: 626, seats: 4, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '6.0L W12', year: 2024 },
    features: ['Diamond quilted leather', 'Rotating display', 'Naim audio'],
    description: 'A grand tourer of unrivalled craftsmanship and effortless power.',
    featured: true, rating: 4.8, reviewsCount: 27,
  }),
  car({
    _id: 'car-bmw-m850i',
    slug: 'bmw-m850i-gran-coupe',
    brand: 'BMW', model: 'M850i Gran Coupé', name: 'BMW M850i Gran Coupé',
    category: 'cat-luxury', categorySlug: 'luxury',
    pricePerDay: 780,
    thumbnail: img('1555215695-3004980ad54e'),
    images: [img('1555215695-3004980ad54e', 1600)],
    specs: { topSpeed: 250, acceleration: 3.7, power: 523, seats: 4, doors: 4,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.4L Twin-Turbo V8', year: 2024 },
    features: ['M Sport differential', 'Bowers & Wilkins audio', 'Glass controls'],
    description: 'A four-door coupé that fuses M Division savagery with executive comfort.',
    rating: 4.7, reviewsCount: 18,
  }),
  car({
    _id: 'car-audi-rs7',
    slug: 'audi-rs7-sportback',
    brand: 'Audi', model: 'RS 7 Sportback', name: 'Audi RS 7 Sportback',
    category: 'cat-luxury', categorySlug: 'luxury',
    pricePerDay: 720,
    thumbnail: img('1558618666-fcd25c85cd64'),
    images: [img('1558618666-fcd25c85cd64', 1600)],
    specs: { topSpeed: 305, acceleration: 3.5, power: 591, seats: 5, doors: 5,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.0L Twin-Turbo V8', year: 2024 },
    features: ['Quattro AWD', 'Dynamic ride control', 'Carbon styling pack'],
    description: 'Sledgehammer pace dressed as a refined four-door fastback.',
    rating: 4.7, reviewsCount: 21,
  }),
  car({
    _id: 'car-lexus-lc500',
    slug: 'lexus-lc-500',
    brand: 'Lexus', model: 'LC 500', name: 'Lexus LC 500',
    category: 'cat-luxury', categorySlug: 'luxury',
    pricePerDay: 590,
    thumbnail: img('1471479917193-f03537a7c88f'),
    images: [img('1471479917193-f03537a7c88f', 1600)],
    specs: { topSpeed: 270, acceleration: 4.4, power: 471, seats: 4, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '5.0L V8', year: 2024 },
    features: ['Mark Levinson audio', 'Active rear spoiler', 'Hand-stitched leather'],
    description: 'A naturally aspirated V8 grand tourer — sculptural, theatrical, rare.',
    available: false,
    rating: 4.6, reviewsCount: 14,
  }),

  // ───────── SUV (6) ─────────
  car({
    _id: 'car-lambo-urus',
    slug: 'lamborghini-urus',
    brand: 'Lamborghini', model: 'Urus', name: 'Lamborghini Urus',
    category: 'cat-suv', categorySlug: 'suv',
    pricePerDay: 1350,
    thumbnail: img('1614200187524-dc4b892acf16'),
    images: [img('1614200187524-dc4b892acf16', 1600)],
    specs: { topSpeed: 305, acceleration: 3.6, power: 657, seats: 5, doors: 5,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.0L Twin-Turbo V8', year: 2024 },
    features: ['ANIMA driving modes', 'Carbon ceramic brakes', 'Sport exhaust'],
    description: 'The world\'s first Super SUV. Outrageous performance with everyday usability.',
    featured: true, rating: 4.9, reviewsCount: 38,
  }),
  car({
    _id: 'car-range-rover',
    slug: 'range-rover-autobiography',
    brand: 'Range Rover', model: 'Autobiography', name: 'Range Rover Autobiography',
    category: 'cat-suv', categorySlug: 'suv',
    pricePerDay: 850,
    thumbnail: img('1605559424843-9e4c228bf1c2'),
    images: [img('1605559424843-9e4c228bf1c2', 1600)],
    specs: { topSpeed: 250, acceleration: 5.1, power: 523, seats: 5, doors: 5,
      transmission: 'automatic', fuelType: 'hybrid', engine: '4.4L V8 Hybrid', year: 2024 },
    features: ['Executive class rear seats', 'Air suspension', 'Meridian audio'],
    description: 'Refined off-road royalty with unmatched cabin comfort.',
    rating: 4.7, reviewsCount: 24,
  }),
  car({
    _id: 'car-bentayga',
    slug: 'bentley-bentayga',
    brand: 'Bentley', model: 'Bentayga', name: 'Bentley Bentayga',
    category: 'cat-suv', categorySlug: 'suv',
    pricePerDay: 1150,
    thumbnail: img('1549317661-cf369843a2ab'),
    images: [img('1549317661-cf369843a2ab', 1600)],
    specs: { topSpeed: 290, acceleration: 4.4, power: 542, seats: 5, doors: 5,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.0L V8', year: 2024 },
    features: ['Naim premium audio', 'Mood lighting', 'Heated/cooled seats'],
    description: 'A Bentley grand tourer, elevated. Hand-stitched luxury at altitude.',
    rating: 4.8, reviewsCount: 19,
  }),
  car({
    _id: 'car-amg-g63',
    slug: 'mercedes-amg-g63',
    brand: 'Mercedes-AMG', model: 'G 63', name: 'Mercedes-AMG G 63',
    category: 'cat-suv', categorySlug: 'suv',
    pricePerDay: 980,
    thumbnail: img('1519245954527-ddc52e855aba'),
    images: [img('1519245954527-ddc52e855aba', 1600)],
    specs: { topSpeed: 240, acceleration: 4.5, power: 577, seats: 5, doors: 5,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.0L Twin-Turbo V8', year: 2024 },
    features: ['AMG performance exhaust', 'Three differential locks', 'Nappa leather'],
    description: 'Iconic, indestructible, unmistakable. The G-Wagen on AMG steroids.',
    featured: true, rating: 4.9, reviewsCount: 41,
  }),
  car({
    _id: 'car-bmw-x7',
    slug: 'bmw-x7-m50i',
    brand: 'BMW', model: 'X7 M50i', name: 'BMW X7 M50i',
    category: 'cat-suv', categorySlug: 'suv',
    pricePerDay: 720,
    thumbnail: img('1563720360172-67286f246098'),
    images: [img('1563720360172-67286f246098', 1600)],
    specs: { topSpeed: 250, acceleration: 4.5, power: 523, seats: 7, doors: 5,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.4L Twin-Turbo V8', year: 2024 },
    features: ['Three-row seating', 'Sky Lounge panoramic roof', 'Crystal controls'],
    description: 'A flagship seven-seater with V8 thunder and a lounge cabin.',
    rating: 4.6, reviewsCount: 16,
  }),
  car({
    _id: 'car-cayenne-turbo',
    slug: 'porsche-cayenne-turbo-gt',
    brand: 'Porsche', model: 'Cayenne Turbo GT', name: 'Porsche Cayenne Turbo GT',
    category: 'cat-suv', categorySlug: 'suv',
    pricePerDay: 890,
    thumbnail: img('1548269174-00c21e7ae9e0'),
    images: [img('1548269174-00c21e7ae9e0', 1600)],
    specs: { topSpeed: 300, acceleration: 3.3, power: 631, seats: 5, doors: 5,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.0L Twin-Turbo V8', year: 2024 },
    features: ['Carbon roof', 'Rear-axle steering', 'PCCB ceramic brakes'],
    description: 'A track-bred SUV — the fastest Cayenne ever made.',
    available: false,
    rating: 4.8, reviewsCount: 22,
  }),

  // ───────── SPORT (6) ─────────
  car({
    _id: 'car-ferrari-488',
    slug: 'ferrari-488-gtb',
    brand: 'Ferrari', model: '488 GTB', name: 'Ferrari 488 GTB',
    category: 'cat-sport', categorySlug: 'sport',
    pricePerDay: 1650,
    thumbnail: img('1583121274602-3e2820c69888'),
    images: [img('1583121274602-3e2820c69888', 1600)],
    specs: { topSpeed: 330, acceleration: 3.0, power: 661, seats: 2, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '3.9L Twin-Turbo V8', year: 2023 },
    features: ['F1-Trac', 'Carbon fiber package', 'Launch control'],
    description: 'A modern mid-engine icon delivering raw, intoxicating performance.',
    featured: true, rating: 5.0, reviewsCount: 51,
  }),
  car({
    _id: 'car-huracan',
    slug: 'lamborghini-huracan-evo',
    brand: 'Lamborghini', model: 'Huracán EVO', name: 'Lamborghini Huracán EVO',
    category: 'cat-sport', categorySlug: 'sport',
    pricePerDay: 1450,
    thumbnail: img('1544636331-e26879cd4d9b'),
    images: [img('1544636331-e26879cd4d9b', 1600)],
    specs: { topSpeed: 325, acceleration: 2.9, power: 631, seats: 2, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '5.2L V10', year: 2024 },
    features: ['LDVI dynamics', 'Magnetorheological suspension', 'Sport exhaust'],
    description: 'A naturally aspirated V10 symphony. Pure, theatrical Italian performance.',
    featured: true, rating: 4.9, reviewsCount: 44,
  }),
  car({
    _id: 'car-911-gt3',
    slug: 'porsche-911-gt3',
    brand: 'Porsche', model: '911 GT3', name: 'Porsche 911 GT3',
    category: 'cat-sport', categorySlug: 'sport',
    pricePerDay: 1100,
    thumbnail: img('1503376780353-7e6692767b70'),
    images: [img('1503376780353-7e6692767b70', 1600)],
    specs: { topSpeed: 318, acceleration: 3.4, power: 502, seats: 2, doors: 2,
      transmission: 'manual', fuelType: 'petrol', engine: '4.0L Flat-6', year: 2024 },
    features: ['Track-tuned suspension', 'Carbon roof', 'PCCB brakes'],
    description: 'The driver\'s 911. Surgical, scream-redline precision.',
    rating: 4.9, reviewsCount: 36,
  }),
  car({
    _id: 'car-mclaren-720s',
    slug: 'mclaren-720s',
    brand: 'McLaren', model: '720S', name: 'McLaren 720S',
    category: 'cat-sport', categorySlug: 'sport',
    pricePerDay: 1750,
    thumbnail: img('1563019650-ec0de49aff6b'),
    images: [img('1563019650-ec0de49aff6b', 1600)],
    specs: { topSpeed: 341, acceleration: 2.8, power: 710, seats: 2, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.0L Twin-Turbo V8', year: 2024 },
    features: ['Dihedral doors', 'Active aerodynamics', 'Carbon MonoCage'],
    description: 'British engineering at its most relentless — alien styling, hyperdrive pace.',
    featured: true, rating: 4.9, reviewsCount: 29,
  }),
  car({
    _id: 'car-aston-db11',
    slug: 'aston-martin-db11',
    brand: 'Aston Martin', model: 'DB11 V12', name: 'Aston Martin DB11 V12',
    category: 'cat-sport', categorySlug: 'sport',
    pricePerDay: 1050,
    thumbnail: img('1619682817481-d53b73db06be'),
    images: [img('1619682817481-d53b73db06be', 1600)],
    specs: { topSpeed: 322, acceleration: 3.9, power: 630, seats: 4, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '5.2L Twin-Turbo V12', year: 2024 },
    features: ['Adaptive damping', 'Bang & Olufsen audio', 'Hand-stitched leather'],
    description: 'A grand tourer with cinematic presence and V12 thunder.',
    rating: 4.7, reviewsCount: 17,
  }),
  car({
    _id: 'car-audi-r8',
    slug: 'audi-r8-v10-performance',
    brand: 'Audi', model: 'R8 V10 Performance', name: 'Audi R8 V10 Performance',
    category: 'cat-sport', categorySlug: 'sport',
    pricePerDay: 1180,
    thumbnail: img('1607853202273-797f1c22a38e'),
    images: [img('1607853202273-797f1c22a38e', 1600)],
    specs: { topSpeed: 331, acceleration: 3.1, power: 602, seats: 2, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '5.2L V10', year: 2024 },
    features: ['Quattro AWD', 'Magnetic ride', 'Carbon engine bay'],
    description: 'The civilised supercar — V10 fury wrapped in everyday usability.',
    available: false,
    rating: 4.8, reviewsCount: 25,
  }),

  // ───────── ELECTRIC (4) ─────────
  car({
    _id: 'car-tesla-plaid',
    slug: 'tesla-model-s-plaid',
    brand: 'Tesla', model: 'Model S Plaid', name: 'Tesla Model S Plaid',
    category: 'cat-electric', categorySlug: 'electric',
    pricePerDay: 650,
    thumbnail: img('1617788138017-80ad40651399'),
    images: [img('1617788138017-80ad40651399', 1600)],
    specs: { topSpeed: 322, acceleration: 2.1, power: 1020, seats: 5, doors: 4,
      transmission: 'automatic', fuelType: 'electric', engine: 'Tri-Motor AWD', year: 2024 },
    features: ['Autopilot', '17" cinematic display', 'Yoke steering'],
    description: 'The fastest production sedan in the world. Silent, savage acceleration.',
    featured: true, rating: 4.7, reviewsCount: 58,
  }),
  car({
    _id: 'car-taycan',
    slug: 'porsche-taycan-turbo-s',
    brand: 'Porsche', model: 'Taycan Turbo S', name: 'Porsche Taycan Turbo S',
    category: 'cat-electric', categorySlug: 'electric',
    pricePerDay: 950,
    thumbnail: img('1619767886558-efdc259cde1a'),
    images: [img('1619767886558-efdc259cde1a', 1600)],
    specs: { topSpeed: 260, acceleration: 2.4, power: 750, seats: 4, doors: 4,
      transmission: 'automatic', fuelType: 'electric', engine: 'Dual-Motor AWD', year: 2024 },
    features: ['800V architecture', 'Adaptive air suspension', 'Burmester 3D'],
    description: 'Porsche dynamics meet electric instant torque. The ultimate EV GT.',
    rating: 4.8, reviewsCount: 33,
  }),
  car({
    _id: 'car-lucid-air',
    slug: 'lucid-air-sapphire',
    brand: 'Lucid', model: 'Air Sapphire', name: 'Lucid Air Sapphire',
    category: 'cat-electric', categorySlug: 'electric',
    pricePerDay: 1090,
    thumbnail: img('1620891549027-942fdc95d3f5'),
    images: [img('1620891549027-942fdc95d3f5', 1600)],
    specs: { topSpeed: 330, acceleration: 1.9, power: 1234, seats: 5, doors: 4,
      transmission: 'automatic', fuelType: 'electric', engine: 'Tri-Motor AWD', year: 2024 },
    features: ['Glass cockpit', '900V architecture', 'Ultra-luxury cabin'],
    description: 'America\'s answer to electric hyper-luxury. Cleaner, faster, quieter.',
    available: false,
    rating: 4.7, reviewsCount: 12,
  }),
  car({
    _id: 'car-eqs',
    slug: 'mercedes-eqs-580',
    brand: 'Mercedes-Benz', model: 'EQS 580', name: 'Mercedes-Benz EQS 580',
    category: 'cat-electric', categorySlug: 'electric',
    pricePerDay: 580,
    thumbnail: img('1635008361017-46b7e4c3f5e1'),
    images: [img('1635008361017-46b7e4c3f5e1', 1600)],
    specs: { topSpeed: 210, acceleration: 4.1, power: 516, seats: 5, doors: 4,
      transmission: 'automatic', fuelType: 'electric', engine: 'Dual-Motor AWD', year: 2024 },
    features: ['MBUX Hyperscreen', 'Rear-axle steering', 'Air balance pack'],
    description: 'A whisper-silent flagship — the S-Class reimagined for electrons.',
    rating: 4.6, reviewsCount: 19,
  }),

  // ───────── CONVERTIBLE (3) ─────────
  car({
    _id: 'car-aston-vantage',
    slug: 'aston-martin-vantage-roadster',
    brand: 'Aston Martin', model: 'Vantage Roadster', name: 'Aston Martin Vantage Roadster',
    category: 'cat-convertible', categorySlug: 'convertible',
    pricePerDay: 1200,
    thumbnail: img('1542362567-b07e54358753'),
    images: [img('1542362567-b07e54358753', 1600)],
    specs: { topSpeed: 314, acceleration: 3.7, power: 503, seats: 2, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.0L Twin-Turbo V8', year: 2024 },
    features: ['K-fold soft top', 'Sport Plus mode', 'Bridge of Weir leather'],
    description: 'British coachwork meets soaring V8 thunder. Top down, top form.',
    featured: true, rating: 4.8, reviewsCount: 22,
  }),
  car({
    _id: 'car-portofino',
    slug: 'ferrari-portofino-m',
    brand: 'Ferrari', model: 'Portofino M', name: 'Ferrari Portofino M',
    category: 'cat-convertible', categorySlug: 'convertible',
    pricePerDay: 1380,
    thumbnail: img('1592198084033-aade902d1aae'),
    images: [img('1592198084033-aade902d1aae', 1600)],
    specs: { topSpeed: 320, acceleration: 3.45, power: 612, seats: 4, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '3.9L Twin-Turbo V8', year: 2024 },
    features: ['Retractable hard top', 'Manettino dial', 'JBL Professional audio'],
    description: 'A folding-roof Ferrari with everyday GT manners and prancing-horse pace.',
    rating: 4.8, reviewsCount: 20,
  }),
  car({
    _id: 'car-bmw-m8',
    slug: 'bmw-m8-cabriolet',
    brand: 'BMW', model: 'M8 Competition Cabriolet', name: 'BMW M8 Competition Cabriolet',
    category: 'cat-convertible', categorySlug: 'convertible',
    pricePerDay: 920,
    thumbnail: img('1612544448445-b8232cff3b6c'),
    images: [img('1612544448445-b8232cff3b6c', 1600)],
    specs: { topSpeed: 305, acceleration: 3.3, power: 617, seats: 4, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '4.4L Twin-Turbo V8', year: 2024 },
    features: ['M Drift Analyser', 'Carbon ceramic brakes', 'Soft-top in 15s'],
    description: 'A four-seat drop-top M car — cruise tool and track weapon, all at once.',
    rating: 4.7, reviewsCount: 14,
  }),

  // ───────── CLASSIC (3) ─────────
  car({
    _id: 'car-shelby-gt500',
    slug: 'ford-mustang-shelby-gt500',
    brand: 'Ford', model: 'Mustang Shelby GT500', name: 'Ford Mustang Shelby GT500',
    category: 'cat-classic', categorySlug: 'classic',
    pricePerDay: 540,
    thumbnail: img('1494976388531-d1058494cdd8'),
    images: [img('1494976388531-d1058494cdd8', 1600)],
    specs: { topSpeed: 290, acceleration: 3.3, power: 760, seats: 4, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '5.2L Supercharged V8', year: 2022 },
    features: ['Track-tuned MagneRide', 'Recaro seats', 'Carbon fibre wing'],
    description: 'American muscle taken to its supercharged extreme.',
    rating: 4.6, reviewsCount: 18,
  }),
  car({
    _id: 'car-corvette-c8',
    slug: 'chevrolet-corvette-c8-z06',
    brand: 'Chevrolet', model: 'Corvette C8 Z06', name: 'Chevrolet Corvette C8 Z06',
    category: 'cat-classic', categorySlug: 'classic',
    pricePerDay: 690,
    thumbnail: img('1542228262-3d663b306a53'),
    images: [img('1542228262-3d663b306a53', 1600)],
    specs: { topSpeed: 314, acceleration: 2.6, power: 670, seats: 2, doors: 2,
      transmission: 'automatic', fuelType: 'petrol', engine: '5.5L Flat-Plane V8', year: 2023 },
    features: ['Flat-plane V8', 'Magnetic ride', 'Targa roof'],
    description: 'Mid-engine American performance at a fraction of European prices.',
    rating: 4.7, reviewsCount: 21,
  }),
  car({
    _id: 'car-mercedes-pagoda',
    slug: 'mercedes-280-sl-pagoda',
    brand: 'Mercedes-Benz', model: '280 SL Pagoda', name: 'Mercedes-Benz 280 SL Pagoda',
    category: 'cat-classic', categorySlug: 'classic',
    pricePerDay: 850,
    thumbnail: img('1503945438517-f65904a52ce6'),
    images: [img('1503945438517-f65904a52ce6', 1600)],
    specs: { topSpeed: 200, acceleration: 9.0, power: 170, seats: 2, doors: 2,
      transmission: 'manual', fuelType: 'petrol', engine: '2.8L Inline-6', year: 1971 },
    features: ['Concours-restored', 'Removable hardtop', 'Period leather'],
    description: 'A timeless icon of 60s sophistication, mechanically restored to perfection.',
    available: false,
    featured: true, rating: 4.9, reviewsCount: 9,
  }),
];

const reviews = [
  {
    _id: 'rev-1', name: 'Elvin Mammadov', role: 'CEO, Caspian Holdings',
    avatar: 'https://i.pravatar.cc/150?img=12', rating: 5,
    comment: 'Booked the Phantom for a corporate event. Flawless service from key handover to return. The car was immaculate.',
    featured: true, createdAt: now,
  },
  {
    _id: 'rev-2', name: 'Aysel Rzayeva', role: 'Founder, Studio Aysel',
    avatar: 'https://i.pravatar.cc/150?img=47', rating: 5,
    comment: 'Velocity made my wedding day unforgettable. The Bentley was breathtaking and the chauffeur was a true professional.',
    featured: true, createdAt: now,
  },
  {
    _id: 'rev-3', name: 'Rashid Aliyev', role: 'Architect',
    avatar: 'https://i.pravatar.cc/150?img=33', rating: 5,
    comment: 'I rent the Huracán every summer. Every single time the experience is better than the last.',
    featured: true, createdAt: now,
  },
  {
    _id: 'rev-4', name: 'Lala Hasanova', role: 'Travel Influencer',
    avatar: 'https://i.pravatar.cc/150?img=49', rating: 5,
    comment: 'The Range Rover took us across Gabala without a second thought. Pure refinement.',
    featured: true, createdAt: now,
  },
  {
    _id: 'rev-5', name: 'Murad Quliyev', role: 'Investor',
    avatar: 'https://i.pravatar.cc/150?img=53', rating: 4,
    comment: 'Delivery was on time, paperwork was painless. Will rent again.',
    featured: false, createdAt: now,
  },
  {
    _id: 'rev-6', name: 'Nigar Ismayilova', role: 'Lawyer',
    avatar: 'https://i.pravatar.cc/150?img=20', rating: 5,
    comment: 'The Taycan is a revelation. Booking through Velocity was as effortless as the car itself.',
    featured: true, createdAt: now,
  },
  {
    _id: 'rev-7', name: 'Tural Nuriyev', role: 'Tech Founder',
    avatar: 'https://i.pravatar.cc/150?img=15', rating: 5,
    comment: 'Outstanding fleet, outstanding people. Velocity sets the bar.',
    featured: false, createdAt: now,
  },
  {
    _id: 'rev-8', name: 'Sevda Akhundova', role: 'Event Producer',
    avatar: 'https://i.pravatar.cc/150?img=44', rating: 5,
    comment: 'They coordinated three cars for a film shoot — flawlessly. Trusted partners.',
    featured: false, createdAt: now,
  },
];

const faqs = [
  {
    _id: 'faq-1', order: 1, category: 'booking',
    question: 'How do I make a reservation?',
    answer:
      'Choose your car, set the pickup and return dates, and submit the booking form. Our team confirms via WhatsApp or email within 30 minutes.',
  },
  {
    _id: 'faq-2', order: 2, category: 'requirements',
    question: 'What documents do I need?',
    answer:
      'A valid driver\'s licence (held for at least 3 years), national ID or passport, and a credit card matching the renter\'s name.',
  },
  {
    _id: 'faq-3', order: 3, category: 'requirements',
    question: 'What is the minimum age to rent?',
    answer: 'The minimum age is 25 for our Luxury, Sport and SUV classes, and 21 for the Electric class.',
  },
  {
    _id: 'faq-4', order: 4, category: 'pricing',
    question: 'Is insurance included?',
    answer:
      'Yes. Comprehensive insurance with collision damage waiver is included on every rental. Additional coverage is optional at checkout.',
  },
  {
    _id: 'faq-5', order: 5, category: 'pricing',
    question: 'Do you require a security deposit?',
    answer:
      'A refundable security deposit is held on your card during the rental. Amount depends on the category — typically $1,000 to $5,000.',
  },
  {
    _id: 'faq-6', order: 6, category: 'logistics',
    question: 'Do you deliver the car to my hotel or airport?',
    answer:
      'Yes, complimentary delivery is available within Baku city limits. Airport and out-of-city deliveries are available for a fee.',
  },
  {
    _id: 'faq-7', order: 7, category: 'logistics',
    question: 'Can I rent for less than a day?',
    answer:
      'Our minimum rental is 24 hours. Hourly photoshoot or event packages can be arranged on request.',
  },
  {
    _id: 'faq-8', order: 8, category: 'policy',
    question: 'What is your cancellation policy?',
    answer:
      'Free cancellation up to 48 hours before the pickup. Within 48 hours, a 30% fee applies. No-shows are non-refundable.',
  },
];

const blogs = [
  {
    _id: 'blog-1', slug: 'rolls-royce-phantom-experience',
    title: 'A Day in the Rolls-Royce Phantom',
    excerpt: 'We took the flagship Phantom from the Old City to the Caspian shoreline. This is what unbothered luxury feels like.',
    content:
      'The Phantom does not move you — it floats you. From the magnetic door release to the starlight headliner, every detail is engineered to insulate you from ordinary life. We spent a full day with the latest Phantom Series II in the streets of Baku and along Bilgah\'s coastline...',
    cover: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?auto=format&fit=crop&w=1600&q=80',
    author: 'Velocity Editorial', tags: ['phantom', 'luxury', 'review'],
    publishedAt: now, createdAt: now,
  },
  {
    _id: 'blog-2', slug: 'how-to-choose-a-supercar-for-the-weekend',
    title: 'How to Choose a Supercar for the Weekend',
    excerpt: 'Ferrari, Lamborghini or Porsche? A practical guide to picking the right machine for your getaway.',
    content:
      'Each marque tells a different story. The Ferrari is theatre. The Lamborghini is opera. The Porsche is precision. Here\'s how to decide which voice you want behind your weekend...',
    cover: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1600&q=80',
    author: 'Velocity Editorial', tags: ['sport', 'guide'],
    publishedAt: now, createdAt: now,
  },
  {
    _id: 'blog-3', slug: 'electric-luxury-the-taycan-and-beyond',
    title: 'Electric Luxury: The Taycan and Beyond',
    excerpt: 'Silent power is rewriting what luxury motoring means. Here\'s why our clients are switching.',
    content:
      'The first time you launch a Taycan Turbo S, the silence is louder than any V8. Electric performance is no longer a compromise...',
    cover: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1600&q=80',
    author: 'Velocity Editorial', tags: ['electric', 'taycan', 'future'],
    publishedAt: now, createdAt: now,
  },
  {
    _id: 'blog-4', slug: 'wedding-day-fleet-curation',
    title: 'Wedding Day Fleet Curation',
    excerpt: 'Three rules we follow when curating cars for the most important day of your life.',
    content:
      'A wedding fleet is more than transportation — it\'s memory. Here\'s how we curate cars that match the venue, the gown, and the moment...',
    cover: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1600&q=80',
    author: 'Velocity Editorial', tags: ['weddings', 'service'],
    publishedAt: now, createdAt: now,
  },
];

module.exports = {
  cars,
  categories,
  bookings: [],
  reviews,
  blogs,
  faqs,
};
